"use client";

import { useState } from "react";
import type { Account } from "@/lib/types";
import { formatUSDExact } from "@/lib/format";
import { ZoneHeader } from "@/components/workspace/ZoneHeader";

interface ScriptResponse {
  script: string;
  source: "gemini" | "template";
  reason?: string;
}

export function RecommendationZone({ account }: { account: Account }) {
  const [script, setScript] = useState<ScriptResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  const needsReview = account.needs_review || !account.recommended_policy;

  async function generate() {
    setLoading(true);
    setError(null);
    setCopied(false);
    try {
      const res = await fetch("/api/generate-script", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          companyUuid: account.company_uuid,
          amountDue: account.amount_due_usd,
          dpdDays: account.dpd_days,
          segment: account.segment,
          policy: account.recommended_policy,
          policyRule: account.policy_rule_fired,
          upfrontRequired: account.upfront_required_usd,
        }),
      });
      if (!res.ok) throw new Error(`Request failed (${res.status})`);
      const data = (await res.json()) as ScriptResponse;
      setScript(data);
    } catch (e) {
      setError(
        e instanceof Error ? e.message : "Could not generate the script.",
      );
    } finally {
      setLoading(false);
    }
  }

  async function copy() {
    if (!script) return;
    await navigator.clipboard.writeText(script.script);
    setCopied(true);
    setTimeout(() => setCopied(false), 1500);
  }

  return (
    <section className="card p-5">
      <ZoneHeader
        index={2}
        title="Negotiation recommendation"
        trailing={
          <span className="hidden items-center gap-1.5 text-[12px] text-ink-muted sm:flex">
            <LockIcon />
            Deterministic · pre-computed
          </span>
        }
      />

      {needsReview ? (
        <ReviewNotice account={account} />
      ) : (
        <>
          <div className="grid gap-4 sm:grid-cols-3">
            <div className="sm:col-span-2">
              <span className="eyebrow">Recommended policy</span>
              <div className="mt-1.5 text-[18px] font-semibold tracking-tight text-ink">
                {account.recommended_policy}
              </div>
              {account.policy_rule_fired && (
                <code className="tnum mt-2 inline-block rounded-[5px] border border-[var(--line-strong)] bg-[var(--surface-2)] px-2 py-1 text-[12px] text-ink-secondary">
                  {account.policy_rule_fired}
                </code>
              )}
            </div>
            <div className="rounded-[8px] border border-[var(--line)] bg-[var(--surface-2)] p-3">
              <span className="eyebrow">Upfront required</span>
              <div className="tnum mt-1 text-[20px] font-semibold tracking-tight text-ink">
                {account.upfront_required_usd
                  ? formatUSDExact(account.upfront_required_usd)
                  : "None"}
              </div>
            </div>
          </div>

          {/* Script generation */}
          <div className="mt-5 border-t border-[var(--line)] pt-4">
            <div className="flex items-center justify-between gap-3">
              <div>
                <span className="text-[13px] font-semibold text-ink">
                  Negotiation script
                </span>
                <p className="mt-0.5 text-[12px] text-ink-muted">
                  Spanish · generated by Gemini from the policy above
                </p>
              </div>
              <button
                className="btn btn-primary"
                onClick={generate}
                disabled={loading}
              >
                {loading ? (
                  <>
                    <Spinner /> Generating…
                  </>
                ) : script ? (
                  "Regenerate"
                ) : (
                  <>
                    <SparkIcon /> Generate script
                  </>
                )}
              </button>
            </div>

            {error && (
              <p className="mt-3 text-[13px] text-[var(--critical)]">{error}</p>
            )}

            {script && (
              <div className="mt-4 rounded-[10px] border border-[var(--line)] bg-[var(--surface-2)]">
                <div className="flex items-center justify-between border-b border-[var(--line)] px-4 py-2">
                  <span className="inline-flex items-center gap-1.5 text-[12px] font-medium text-ink-muted">
                    <span
                      className="dot h-1.5 w-1.5 rounded-full"
                      style={{
                        background:
                          script.source === "gemini"
                            ? "var(--good)"
                            : "var(--warning)",
                      }}
                    />
                    {script.source === "gemini"
                      ? "Generated by Gemini"
                      : "Template fallback"}
                    {script.source === "template" && script.reason
                      ? ` · ${script.reason}`
                      : ""}
                  </span>
                  <button
                    className="text-[12px] font-medium text-accent hover:underline"
                    onClick={copy}
                  >
                    {copied ? "Copied" : "Copy"}
                  </button>
                </div>
                <p className="whitespace-pre-wrap px-4 py-4 text-[13px] leading-relaxed text-ink">
                  {script.script}
                </p>
              </div>
            )}
          </div>
        </>
      )}
    </section>
  );
}

function ReviewNotice({ account }: { account: Account }) {
  return (
    <div className="rounded-[10px] border border-[var(--warning)]/30 bg-[var(--warning-wash)] p-4">
      <div className="flex items-start gap-3">
        <span className="mt-0.5 text-[var(--warning)]">
          <WarnIcon />
        </span>
        <div>
          <p className="text-[14px] font-semibold text-ink">
            Cannot recommend policy: data verification required
          </p>
          <p className="mt-1 text-[13px] text-ink-secondary">
            The upstream pipeline did not compute a policy because this record was
            flagged for review. Resolve the flags below before negotiating.
          </p>
          <div className="mt-3 flex flex-wrap gap-2">
            {account.data_quality_flags.length > 0 ? (
              account.data_quality_flags.map((flag) => (
                <span key={flag} className="flag-chip">
                  <WarnIcon />
                  {flag}
                </span>
              ))
            ) : (
              <span className="flag-chip">
                <WarnIcon />
                Marked needs-review by pipeline
              </span>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function Spinner() {
  return (
    <svg
      className="animate-spin"
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
    >
      <circle
        cx="12"
        cy="12"
        r="9"
        stroke="currentColor"
        strokeWidth="3"
        strokeOpacity="0.25"
      />
      <path
        d="M21 12a9 9 0 0 0-9-9"
        stroke="currentColor"
        strokeWidth="3"
        strokeLinecap="round"
      />
    </svg>
  );
}

function SparkIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="currentColor"
      aria-hidden
    >
      <path d="M12 2l1.9 5.8a2 2 0 0 0 1.3 1.3L21 11l-5.8 1.9a2 2 0 0 0-1.3 1.3L12 20l-1.9-5.8a2 2 0 0 0-1.3-1.3L3 11l5.8-1.9a2 2 0 0 0 1.3-1.3L12 2z" />
    </svg>
  );
}

function LockIcon() {
  return (
    <svg
      width="12"
      height="12"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
    >
      <rect x="3" y="11" width="18" height="11" rx="2" />
      <path d="M7 11V7a5 5 0 0 1 10 0v4" />
    </svg>
  );
}

function WarnIcon() {
  return (
    <svg
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10.29 3.86 1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0Z" />
      <path d="M12 9v4" />
      <path d="M12 17h.01" />
    </svg>
  );
}
